# Generated by Django 4.0 on 2021-12-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioPhoneCall',
            fields=[
                ('alertplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabotapp.alertplugin')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cabotapp.alertplugin',),
        ),
        migrations.CreateModel(
            name='TwilioSMS',
            fields=[
                ('alertplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabotapp.alertplugin')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cabotapp.alertplugin',),
        ),
        migrations.CreateModel(
            name='TwilioUserData',
            fields=[
                ('alertpluginuserdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabotapp.alertpluginuserdata')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cabotapp.alertpluginuserdata',),
        ),
    ]
